---
abstract: 'Rose::DB with auto-reconnect to server'
author:
  - 'Peter Karman <karman@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120530'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Rose-DBx-AutoReconnect
no_index:
  directory:
    - t
    - inc
requires:
  Rose::DB: 0.743
  Test::More: 0
version: 0.04
