--- #YAML:1.0
name:                Rose-DBx-AutoReconnect
version:             0.01
abstract:            Rose::DB with auto-reconnect to server
license:             ~
author:              
    - Peter Karman <karman@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Rose::DB:                      0.743
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
